# See rosbag2_transport::PlayOptions::playback_duration
# It will be set as the difference of playback_until with the
# effective playback start time point.
builtin_interfaces/Time playback_until
---
# returns false when another playback execution is running, otherwise true
bool success
